[theme]
primaryColor = "#2E75B6"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F6FA"
textColor = "#172B4D"
font = "sans serif"

[server]
headless = true
enableCORS = true

[browser]
gatherUsageStats = false
